project:
  type: website
  output-dir: docs

execute: 
  freeze: true

website:
  title: "Joshua Marie"
  favicon: "assets/jm-favicon.png"
  navbar:
    background: light
    left:
      # - text: "Services"
      #   href: services.qmd
      - text: "Contact"
        href: contacts.qmd
      - text: "My resources"
        href: resources.qmd
      - text: "Posts"
        href: posts/index.qmd
    right:
      - icon: github
        href: https://github.com/joshuamarie
        aria-label: "GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/joshuamarie/
        aria-label: "LinkedIn"
      - icon: envelope             
        href: mailto:joshua.marie.k@gmail.com
        aria-label: "Email"
      - icon: rss  
        href: index.xml
        aria-label: "RSS Feed"
  page-footer:
    center: "Design inspired by [Geeky Hugo](https://github.com/statichunt/geeky-hugo)"
  twitter-card: true
  repo-url: https://github.com/joshuamarie/joshuamarie.github.io
  repo-actions: [edit, issue]
  repo-branch: main
  site-url: https://joshuamarie.com

highlight-style: pygments
 
format:
  html:
    include-in-header:
      - text: |
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9842567530621468" crossorigin="anonymous"></script>
    comments:
      utterances:
        repo: joshuamarie/joshuamarie.github.io
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    fontsize: 1.1em
    theme: theming.scss
    css: 
      - styles/base.css
      - styles/layout.css
      - styles/hero.css
      - styles/cards.css
      - styles/about.css
      - styles/dark-mode.css
      # - styles/components.css
    mainfont: "Mulish"
  